### ISSUE TITLE
Billing info block in CiviCRM 4.6.8

### ISSUE THREAD

**Issue by robbrandt** [TobiasLounsbury/civicrm-simple-workflow#1]
Sometime between 4.6.3 and 4.6.8 CiviCRM added a feature to Contribution forms where a total price recalculation triggers some javascript that makes the billing info block appear/disappear on the page.  This is a problem for the Workflow because it puts the billing info block on every page where a selection is made.

**Comment by TobiasLounsbury** [comment]
@robbrandt Thank you for the patch!
I've cherry picked the functional lines out of the linked PR and closed it. I'm going to close this issue as well.
